
package com.microsoft.schemas.livesearch._2008._03.search;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LiveSearchPortType", targetNamespace = "http://schemas.microsoft.com/LiveSearch/2008/03/Search")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LiveSearchPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.schemas.livesearch._2008._03.search.SearchResponse>
     */
    @WebMethod(operationName = "Search", action = "http://schemas.microsoft.com/LiveSearch/2008/03/Search/Search")
    public Response<SearchResponse> searchAsync(
        @WebParam(name = "SearchRequest", targetNamespace = "http://schemas.microsoft.com/LiveSearch/2008/03/Search", partName = "parameters")
        SearchRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "Search", action = "http://schemas.microsoft.com/LiveSearch/2008/03/Search/Search")
    public Future<?> searchAsync(
        @WebParam(name = "SearchRequest", targetNamespace = "http://schemas.microsoft.com/LiveSearch/2008/03/Search", partName = "parameters")
        SearchRequest parameters,
        @WebParam(name = "SearchResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SearchResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.schemas.livesearch._2008._03.search.SearchResponse
     */
    @WebMethod(operationName = "Search", action = "http://schemas.microsoft.com/LiveSearch/2008/03/Search/Search")
    @WebResult(name = "SearchResponse", targetNamespace = "http://schemas.microsoft.com/LiveSearch/2008/03/Search", partName = "parameters")
    public SearchResponse search(
        @WebParam(name = "SearchRequest", targetNamespace = "http://schemas.microsoft.com/LiveSearch/2008/03/Search", partName = "parameters")
        SearchRequest parameters);

}
