
package com.microsoft.schemas.livesearch._2008._03.search;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LiveSearchService", targetNamespace = "http://schemas.microsoft.com/LiveSearch/2008/03/Search", wsdlLocation = "http://api.search.live.net/search.wsdl?49EB1BB201E8950D5CEE9AC199C7ADD7CE08AA40")
public class LiveSearchService
    extends Service
{

    private final static URL LIVESEARCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.microsoft.schemas.livesearch._2008._03.search.LiveSearchService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.microsoft.schemas.livesearch._2008._03.search.LiveSearchService.class.getResource(".");
            url = new URL(baseUrl, "http://api.search.live.net/search.wsdl?49EB1BB201E8950D5CEE9AC199C7ADD7CE08AA40");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://api.search.live.net/search.wsdl?49EB1BB201E8950D5CEE9AC199C7ADD7CE08AA40', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LIVESEARCHSERVICE_WSDL_LOCATION = url;
    }

    public LiveSearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LiveSearchService() {
        super(LIVESEARCHSERVICE_WSDL_LOCATION, new QName("http://schemas.microsoft.com/LiveSearch/2008/03/Search", "LiveSearchService"));
    }

    /**
     * 
     * @return
     *     returns LiveSearchPortType
     */
    @WebEndpoint(name = "LiveSearchPort")
    public LiveSearchPortType getLiveSearchPort() {
        return super.getPort(new QName("http://schemas.microsoft.com/LiveSearch/2008/03/Search", "LiveSearchPort"), LiveSearchPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LiveSearchPortType
     */
    @WebEndpoint(name = "LiveSearchPort")
    public LiveSearchPortType getLiveSearchPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/LiveSearch/2008/03/Search", "LiveSearchPort"), LiveSearchPortType.class, features);
    }

}
